# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(608, 467)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 591, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.addButton.setStyleSheet("background-color: cyan;\n"
"font-style: italic;")
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 3, 0, 1, 1)
        self.amountEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.amountEdit.setObjectName("amountEdit")
        self.gridLayout.addWidget(self.amountEdit, 2, 1, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 2, 0, 1, 1)
        self.removeButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.removeButton.setStyleSheet("background-color: cyan;\n"
"font-style: italic;")
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.exportButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.exportButton.setObjectName("exportButton")
        self.gridLayout.addWidget(self.exportButton, 5, 0, 1, 1)
        self.productList = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.productList.setObjectName("productList")
        self.gridLayout.addWidget(self.productList, 4, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nazwa"))
        self.addButton.setText(_translate("Dialog", "Dodaj"))
        self.removeButton.setText(_translate("Dialog", "Usuń"))
        self.label_2.setText(_translate("Dialog", "Ilość"))
        self.exportButton.setText(_translate("Dialog", "Eksportuj"))
